#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely.
#In between each iteration of the loop, add a sleep 2
While true; do
   echo "To infinity and beyond"
   sleep 2
done
